version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "Nahuelluca20"
    assignees:
      - "Nahuelluca20"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "weekly"
    reviewers:
      - "Nahuelluca20"
    assignees:
      - "Nahuelluca20"